stages:
  - test
  - package

test-job:
  image: maven:3.3-jdk-8
  script:
  - mvn test
  -stage: test

package-war-job:
  image: maven:3.3-jdk-8
  stage: package
  script:
   - mvn package -DskipTests
  artifacts:
    paths:
     - target/pronomaster/*
    expire_in: 1 weeks

package-image-job:
  variables:
    CONTAINER_IMAGE: registry.gitlab.com/$CI_PROJECT_PATH
    DOCKER_HOST: tcp://docker:2375
    DOCKER_DRIVER: overlay2
  services:
   - docker:dind
  before_script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
  image: docker:stable
  script:
   - docker build -t $CONTAINER_IMAGE:latest .
   - docker push $CONTAINER_IMAGE:latest
  stage: package
  dependencies:
   -package-war-job


