version : "3"
services:
  application:
    image: pronomaster-app:latest
    volumes:
    - /home/docker/files:/DATA/FILES
    environment:
      REPERTOIRE_PRINCIPAL: "/DATA/FILES/"
      JDBC_HOST: database
      JDBC_PORT: 3306
      JDBC_NAME: PronoMaster3
      JDBC_USER: root
      JDBC_PASSWORD:
    ports:
    - "8888:8080"
  database:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./docker/bdd:/docker-entrypoint-initdb.d
